### PR TITLE
Fix test for workflow client

### LINKED ISSUE #13: Fix deepEquals in pkg/client/workflows_test.go
Fix deepEquals in https://github.com/nov1n/kubernetes-workflow/pull/12/files#r63482063.
It should compare the expected struct with the resulting struct and give appropriate errors when they mismatch.

### PR DESCRIPTION
**Pull request by borismattijssen**
* Fixes #13.
* Updates vendors
* Update to hack/test.sh to use godep and check if coverage out file exists

### CODE REVIEW

File: hack/test.sh [hunk 1]
```diff
@@ -1,13 +1,20 @@
...
+[ -d ./bin ] || mkdir bin
 
 godep go build -o bin/workflow
 
 for file in ./pkg/*
 do
-    go test -coverprofile=/tmp/cover.out $file
-    go tool cover -func=/tmp/cover.out
+    CFILE=/tmp/cover.out
+    godep go test -coverprofile=/tmp/cover.out $file
```
Comment (nov1n) [inline hack/test.sh]: Could give every cover file a distinct name, optionally generate. This solves the problem of displaying results twice if no test file is present and will allow coverage services to generate a report + badge.

Comment (borismattijssen) [inline hack/test.sh]: Will fix when we start using the code coverage service.
